[package]
name = "synth-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.17.1"
crossterm = "0.29.0"
fundsp = "0.23.0"
ratatui = "0.30.0"
rodio = "0.21.1"
tokio = {version ="1.49.0", features = ["full"]}
